# Visual Programming for Data Science

# Lab Practical 1

# Group 1

## Question 1

In [1]:
# Import pandas library
import pandas as pd
pd.__version__ # Print pandas version

'2.3.3'

In [2]:
# Load and read raw data
df = pd.read_excel('P1_data.xlsx')
df

    Transaction_ID Customer_Name   Age Product_Category  Total_Spend
0             1001    Customer_1  28.0      electronics       150.50
1             1002    Customer_2  34.0         Clothing        89.99
2             1003    Customer_3  45.0             HOME       210.00
3             1004    Customer_4   NaN      electronics       340.50
4             1005    Customer_5  22.0           beauty        45.00
..             ...           ...   ...              ...          ...
75            1071   Customer_71  39.0      electronics       330.00
76            1072   Customer_72  46.0              NaN       195.00
77            1073   Customer_73  32.0           beauty        85.00
78            1074   Customer_74  51.0      electronics       245.50
79            1075   Customer_75  27.0         Clothing        90.00

[80 rows x 5 columns]

In [3]:
# Print data types of dataset's data
print("The dataset's datatypes")
df.dtypes

The dataset's datatypes

Transaction_ID        int64
Customer_Name        object
Age                 float64
Product_Category     object
Total_Spend         float64
dtype: object

In [4]:
# Print the new shape of the dataset
print(f'''The original shape of the dataset is {df.shape},
where {df.shape[0]} is the number of rows and {df.shape[1]} is the 
number of columns.''')

The original shape of the dataset is (80, 5),
where 80 is the number of rows and 5 is the
number of columns.

In [5]:
# Print the top five rows from the dataset
df.head()

   Transaction_ID Customer_Name   Age Product_Category  Total_Spend
0            1001    Customer_1  28.0      electronics       150.50
1            1002    Customer_2  34.0         Clothing        89.99
2            1003    Customer_3  45.0             HOME       210.00
3            1004    Customer_4   NaN      electronics       340.50
4            1005    Customer_5  22.0           beauty        45.00

In [6]:
# Print the dataset's information
print("The dataset's information")
df.info()

The dataset's information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    80 non-null     int64
 1   Customer_Name     76 non-null     object
 2   Age               73 non-null     float64
 3   Product_Category  73 non-null     object
 4   Total_Spend       80 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.3+ KB

In [7]:
# Print the total null values from each column
print('Total null values from each column')
df.isnull().sum()

Total null values from each column

Transaction_ID      0
Customer_Name       4
Age                 7
Product_Category    7
Total_Spend         0
dtype: int64

The columns containing missing data are "Customer_Name", "Age", and "Product_Category"

## Question 2

In [8]:
# Count duplicates
print(f'Total duplicates: {df.duplicated().sum()}')

Total duplicates: 5

In [9]:
# Show the duplicate rows
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

    Transaction_ID Customer_Name   Age Product_Category  Total_Spend
1             1002    Customer_2  34.0         Clothing        89.99
8             1009    Customer_9  41.0             HOME       180.20
13            1014   Customer_14  31.0      electronics       410.00
16            1002    Customer_2  34.0         Clothing        89.99
26            1026   Customer_26  44.0         Clothing       105.00
28            1009    Customer_9  41.0             HOME       180.20
42            1026   Customer_26  44.0         Clothing       105.00
53            1051   Customer_51  26.0         Clothing        85.00
57            1014   Customer_14  31.0      electronics       410.00
70            1051   Customer_51  26.0         Clothing        85.00

In [10]:
# Display five exact rows that have duplicated values
df[df.duplicated(keep='first')]

    Transaction_ID Customer_Name   Age Product_Category  Total_Spend
16            1002    Customer_2  34.0         Clothing        89.99
28            1009    Customer_9  41.0             HOME       180.20
42            1026   Customer_26  44.0         Clothing       105.00
57            1014   Customer_14  31.0      electronics       410.00
70            1051   Customer_51  26.0         Clothing        85.00

In [11]:
# Drop duplicates and save to df variable
df = df.drop_duplicates(keep='first', inplace=False).copy()
df

    Transaction_ID Customer_Name   Age Product_Category  Total_Spend
0             1001    Customer_1  28.0      electronics       150.50
1             1002    Customer_2  34.0         Clothing        89.99
2             1003    Customer_3  45.0             HOME       210.00
3             1004    Customer_4   NaN      electronics       340.50
4             1005    Customer_5  22.0           beauty        45.00
..             ...           ...   ...              ...          ...
75            1071   Customer_71  39.0      electronics       330.00
76            1072   Customer_72  46.0              NaN       195.00
77            1073   Customer_73  32.0           beauty        85.00
78            1074   Customer_74  51.0      electronics       245.50
79            1075   Customer_75  27.0         Clothing        90.00

[75 rows x 5 columns]

In [12]:
# Calculate the age mean
age_mean = round(df['Age'].mean())
print(f'The age mean is {age_mean}')

The age mean is 37

In [13]:
# Fill missing Age with mean value
df['Age'] = df['Age'].fillna(age_mean).astype(int)
df

    Transaction_ID Customer_Name  Age Product_Category  Total_Spend
0             1001    Customer_1   28      electronics       150.50
1             1002    Customer_2   34         Clothing        89.99
2             1003    Customer_3   45             HOME       210.00
3             1004    Customer_4   37      electronics       340.50
4             1005    Customer_5   22           beauty        45.00
..             ...           ...  ...              ...          ...
75            1071   Customer_71   39      electronics       330.00
76            1072   Customer_72   46              NaN       195.00
77            1073   Customer_73   32           beauty        85.00
78            1074   Customer_74   51      electronics       245.50
79            1075   Customer_75   27         Clothing        90.00

[75 rows x 5 columns]

In [14]:
# Find the mode from product category column
product_mode = df['Product_Category'].mode()[0]
print(f'The product mode is "{product_mode}"')

The product mode is "electronics"

In [15]:
# Fill missing product category with mode value
df['Product_Category'] = df['Product_Category'].fillna(product_mode)
df

    Transaction_ID Customer_Name  Age Product_Category  Total_Spend
0             1001    Customer_1   28      electronics       150.50
1             1002    Customer_2   34         Clothing        89.99
2             1003    Customer_3   45             HOME       210.00
3             1004    Customer_4   37      electronics       340.50
4             1005    Customer_5   22           beauty        45.00
..             ...           ...  ...              ...          ...
75            1071   Customer_71   39      electronics       330.00
76            1072   Customer_72   46      electronics       195.00
77            1073   Customer_73   32           beauty        85.00
78            1074   Customer_74   51      electronics       245.50
79            1075   Customer_75   27         Clothing        90.00

[75 rows x 5 columns]

In [16]:
# Drop rows where Customer_Name is missing
df = df.dropna(subset=['Customer_Name'], inplace=False).copy()
df

    Transaction_ID Customer_Name  Age Product_Category  Total_Spend
0             1001    Customer_1   28      electronics       150.50
1             1002    Customer_2   34         Clothing        89.99
2             1003    Customer_3   45             HOME       210.00
3             1004    Customer_4   37      electronics       340.50
4             1005    Customer_5   22           beauty        45.00
..             ...           ...  ...              ...          ...
75            1071   Customer_71   39      electronics       330.00
76            1072   Customer_72   46      electronics       195.00
77            1073   Customer_73   32           beauty        85.00
78            1074   Customer_74   51      electronics       245.50
79            1075   Customer_75   27         Clothing        90.00

[71 rows x 5 columns]

## Question 3

In [17]:
# Calculate the Q1 and Q3
Q1 = df['Total_Spend'].quantile(0.25)
Q3 = df['Total_Spend'].quantile(0.75)
# Display the value of Q1 and Q3
print(f'The value of Q1 is {Q1}')
print(f'The value of Q3 is {Q3}')

The value of Q1 is 92.75
The value of Q3 is 277.5

In [18]:
# Calculate the IQR
IQR = Q3 - Q1
# Display the value of IQR
print(f'The value of IQR is {IQR}')

The value of IQR is 184.75

In [19]:
# Define and calculate the bounds
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)
# Display the lower bound and upper bound
print(f'The value of lower bound: {lower_bound}')
print(f'The value of upper bound: {upper_bound}')

The value of lower bound: -184.375
The value of upper bound: 554.625

In [20]:
# Filter the outliers data
df = df[(df['Total_Spend'] >= lower_bound) & (df['Total_Spend'] <= upper_bound)]
df

    Transaction_ID Customer_Name  Age Product_Category  Total_Spend
0             1001    Customer_1   28      electronics       150.50
1             1002    Customer_2   34         Clothing        89.99
2             1003    Customer_3   45             HOME       210.00
3             1004    Customer_4   37      electronics       340.50
4             1005    Customer_5   22           beauty        45.00
..             ...           ...  ...              ...          ...
75            1071   Customer_71   39      electronics       330.00
76            1072   Customer_72   46      electronics       195.00
77            1073   Customer_73   32           beauty        85.00
78            1074   Customer_74   51      electronics       245.50
79            1075   Customer_75   27         Clothing        90.00

[66 rows x 5 columns]

In [21]:
# Print the new shape of the dataset
print(f'''The new shape of the dataset is {df.shape},
where {df.shape[0]} is the number of rows and {df.shape[1]} is the 
number of columns.''')

The new shape of the dataset is (66, 5),
where 66 is the number of rows and 5 is the
number of columns.

## Question 4

In [22]:
# Function to categorise the total spending
def categorise_total_spend(total_spend):
    if total_spend < 100:
        return 'Low'
    elif 100 <= total_spend <= 300:
        return 'Medium'
    else:
        return 'High'
# Copy the original dataset
df = df.copy()
# Apply the function to the new column in the dataset
df['Spend_Category'] = df['Total_Spend'].apply(categorise_total_spend)
# Display the current modified dataset
df

,Transaction_ID,Customer_Name,Age,Product_Category,Total_Spend,Spend_Category
0,1001,Customer_1,28,electronics,150.50,Medium
1,1002,Customer_2,34,Clothing,89.99,Low
2,1003,Customer_3,45,HOME,210.00,Medium
3,1004,Customer_4,37,electronics,340.50,High
4,1005,Customer_5,22,beauty,45.00,Low
...,...,...,...,...,...,...
75,1071,Customer_71,39,electronics,330.00,High
76,1072,Customer_72,46,electronics,195.00,Medium
77,1073,Customer_73,32,beauty,85.00,Low
78,1074,Customer_74,51,electronics,245.50,Medium
79,1075,Customer_75,27,Clothing,90.00,Low

In [23]:
# Standardize the product category text to upper case
df['Product_Category'] = df['Product_Category'].str.upper()
df

,Transaction_ID,Customer_Name,Age,Product_Category,Total_Spend,Spend_Category
0,1001,Customer_1,28,ELECTRONICS,150.50,Medium
1,1002,Customer_2,34,CLOTHING,89.99,Low
2,1003,Customer_3,45,HOME,210.00,Medium
3,1004,Customer_4,37,ELECTRONICS,340.50,High
4,1005,Customer_5,22,BEAUTY,45.00,Low
...,...,...,...,...,...,...
75,1071,Customer_71,39,ELECTRONICS,330.00,High
76,1072,Customer_72,46,ELECTRONICS,195.00,Medium
77,1073,Customer_73,32,BEAUTY,85.00,Low
78,1074,Customer_74,51,ELECTRONICS,245.50,Medium
79,1075,Customer_75,27,CLOTHING,90.00,Low

In [24]:
# Save the fully cleaned and transformed dataset as a new file
df.to_csv('final_P1_data.csv', index=False)
# Display the final dataset
df = pd.read_csv('final_P1_data.csv')
df

,Transaction_ID,Customer_Name,Age,Product_Category,Total_Spend,Spend_Category
0,1001,Customer_1,28,ELECTRONICS,150.50,Medium
1,1002,Customer_2,34,CLOTHING,89.99,Low
2,1003,Customer_3,45,HOME,210.00,Medium
3,1004,Customer_4,37,ELECTRONICS,340.50,High
4,1005,Customer_5,22,BEAUTY,45.00,Low
...,...,...,...,...,...,...
61,1071,Customer_71,39,ELECTRONICS,330.00,High
62,1072,Customer_72,46,ELECTRONICS,195.00,Medium
63,1073,Customer_73,32,BEAUTY,85.00,Low
64,1074,Customer_74,51,ELECTRONICS,245.50,Medium
65,1075,Customer_75,27,CLOTHING,90.00,Low

End of the code